/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package br.univates.apresentacao;

import br.univates.negocio.Assinatura;
import br.univates.persistencia.DaoFactory;
import br.univates.source.persistence.IDao;
import br.univates.source.persistence.InvalidKeyException;
import br.univates.source.persistence.KeyViolationException;
import br.univates.source.persistence.NotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class Tela_cad_assin extends javax.swing.JFrame {

    /** Creates new form Tela_cad_assin */

    private Assinatura assi;
    
    public Tela_cad_assin() {
        initComponents();
        this.assi = new Assinatura();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoID = new javax.swing.JTextField();
        lbAssi = new javax.swing.JLabel();
        textoNome = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        lbQualidade = new javax.swing.JLabel();
        lbQtd = new javax.swing.JLabel();
        lbPreco = new javax.swing.JLabel();
        textoQuali = new javax.swing.JTextField();
        textoQtd = new javax.swing.JTextField();
        textoPreco = new javax.swing.JTextField();
        btCancelar = new javax.swing.JButton();
        btCriar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        ButtonAtt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoIDActionPerformed(evt);
            }
        });
        textoID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoIDKeyTyped(evt);
            }
        });

        lbAssi.setText("ID da assinatura");

        textoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNomeActionPerformed(evt);
            }
        });

        lbNome.setText("Nome");

        lbQualidade.setText("Qualidade");

        lbQtd.setText("Quantidadade de dispositivos");

        lbPreco.setText("Preço");

        textoQuali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoQualiActionPerformed(evt);
            }
        });

        textoQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoQtdActionPerformed(evt);
            }
        });

        textoPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPrecoActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btCriar.setText("Cadastrar");
        btCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarActionPerformed(evt);
            }
        });

        btDeletar.setText("Deletar");
        btDeletar.setToolTipText("Só é necessário o ID para essa ação.");
        btDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDeletarMouseEntered(evt);
            }
        });
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        ButtonAtt.setText("Atualizar");
        ButtonAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNome)
                            .addComponent(lbAssi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textoID, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbQtd)
                            .addComponent(lbQualidade)
                            .addComponent(lbPreco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoQuali, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(textoQtd)
                            .addComponent(textoPreco))
                        .addGap(80, 80, 80))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancelar)
                .addGap(18, 18, 18)
                .addComponent(btDeletar)
                .addGap(18, 18, 18)
                .addComponent(ButtonAtt)
                .addGap(18, 18, 18)
                .addComponent(btCriar)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAssi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQualidade)
                    .addComponent(textoQuali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQtd)
                    .addComponent(textoQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPreco)
                    .addComponent(textoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btCriar)
                    .addComponent(btDeletar)
                    .addComponent(ButtonAtt))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void textoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoIDActionPerformed
        
    }//GEN-LAST:event_textoIDActionPerformed

    private void textoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNomeActionPerformed

    private void textoPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPrecoActionPerformed
        double valor;
        if (this.textoPreco.getText().length()!=0){
            try{
                valor=Double.parseDouble(this.textoPreco.getText());
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Esse campo só aceita números.", "Cuidado", JOptionPane.INFORMATION_MESSAGE);
                this.textoPreco.grabFocus();
            }
        }
    }//GEN-LAST:event_textoPrecoActionPerformed

    private void textoQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoQtdActionPerformed
        int valor;
        if (this.textoQtd.getText().length()!=0){
            try{
                valor=Integer.parseInt(this.textoQtd.getText());
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Esse campo só aceita números inteiros.", "Cuidado", JOptionPane.INFORMATION_MESSAGE);
                this.textoQtd.grabFocus();
            }
        }
    }//GEN-LAST:event_textoQtdActionPerformed

    private void textoQualiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoQualiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoQualiActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed
        
        Integer id=Integer.parseInt(this.textoID.getText());
        String nome=this.textoNome.getText();
        String qualidade=this.textoQuali.getText();
        int qtd=Integer.parseInt(this.textoQtd.getText());
        double preco=Double.parseDouble(this.textoPreco.getText());
        
        boolean create = (this.assi.getPk()==0);
        
        this.assi.setPk(id);
        this.assi.setNome(nome);
        this.assi.setQualidade(qualidade);
        this.assi.setQtdMaxDispositivos(qtd);
        this.assi.setPreco(preco);
        
        IDao<Assinatura,Integer> dao= DaoFactory.createAssinaturaDao();
        
        try{
            if(create){
                dao.create(assi);
            }
        } catch (KeyViolationException | InvalidKeyException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage() );
        }
        dispose();
    }//GEN-LAST:event_btCriarActionPerformed

    private void textoIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoIDKeyPressed
        
    }//GEN-LAST:event_textoIDKeyPressed

    private void textoIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoIDKeyTyped
        int valor;
        if (this.textoID.getText().length()!=0){
            try{
                valor=Integer.parseInt(this.textoID.getText());
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Esse campo só aceita números inteiros.", "Cuidado", JOptionPane.INFORMATION_MESSAGE);
                this.textoID.grabFocus();
            }
        }
    }//GEN-LAST:event_textoIDKeyTyped

    private void btDeletarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeletarMouseEntered
        
    }//GEN-LAST:event_btDeletarMouseEntered

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        IDao<Assinatura,Integer> dao= DaoFactory.createAssinaturaDao();
        
        try {
            dao.delete(Integer.parseInt(this.textoID.getText()));
            JOptionPane.showMessageDialog(null, "Deletado.", "Concluído", JOptionPane.INFORMATION_MESSAGE);
        } catch (NotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível deletar.", "Problema", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btDeletarActionPerformed

    private void ButtonAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAttActionPerformed
        IDao<Assinatura,Integer> dao = DaoFactory.createAssinaturaDao();
        
        Integer id=Integer.parseInt(this.textoID.getText());
        String nome=this.textoNome.getText();
        String qualidade=this.textoQuali.getText();
        int qtd=Integer.parseInt(this.textoQtd.getText());
        double preco=Double.parseDouble(this.textoPreco.getText());
        
        boolean update = (this.assi.getPk()==0);
        
        this.assi.setPk(id);
        this.assi.setNome(nome);
        this.assi.setQualidade(qualidade);
        this.assi.setQtdMaxDispositivos(qtd);
        this.assi.setPreco(preco);
        
        try{
            if(update){
                dao.update(assi);
            } else{
                System.out.println("Erro com o ID.");
            }
        } catch (NotFoundException ex) {
            Logger.getLogger(Tela_cad_assin.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_ButtonAttActionPerformed

    /**
     */

    private String nome;
    private String qualidade;
    private int qtd_max;
    private double preco;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAtt;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCriar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JLabel lbAssi;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JLabel lbQtd;
    private javax.swing.JLabel lbQualidade;
    private javax.swing.JTextField textoID;
    private javax.swing.JTextField textoNome;
    private javax.swing.JTextField textoPreco;
    private javax.swing.JTextField textoQtd;
    private javax.swing.JTextField textoQuali;
    // End of variables declaration//GEN-END:variables

}
