/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univates.apresentacao;

import br.univates.persistencia.DaoFactory;

/**
 *
 * @author nicolas.emer
 */
public class Tela_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Tela_Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        Cadastro_Cliente = new javax.swing.JMenuItem();
        Cadastro_Assinatura = new javax.swing.JMenuItem();
        Endereco = new javax.swing.JMenuItem();
        Forma_pagamento = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Pesquisa_Cliente = new javax.swing.JMenuItem();
        Pesquisa_Assinatura = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jMenu3.setText("Cadastro/Atualização");

        Cadastro_Cliente.setText("Cliente");
        Cadastro_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_ClienteActionPerformed(evt);
            }
        });
        jMenu3.add(Cadastro_Cliente);

        Cadastro_Assinatura.setText("Assinatura");
        Cadastro_Assinatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_AssinaturaActionPerformed(evt);
            }
        });
        jMenu3.add(Cadastro_Assinatura);

        Endereco.setText("Endereco");
        Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnderecoActionPerformed(evt);
            }
        });
        jMenu3.add(Endereco);

        Forma_pagamento.setText("Forma_pagamento");
        Forma_pagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Forma_pagamentoActionPerformed(evt);
            }
        });
        jMenu3.add(Forma_pagamento);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Pesquisa");

        Pesquisa_Cliente.setText("Cliente");
        Pesquisa_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pesquisa_ClienteActionPerformed(evt);
            }
        });
        jMenu1.add(Pesquisa_Cliente);

        Pesquisa_Assinatura.setText("Assinatura");
        Pesquisa_Assinatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pesquisa_AssinaturaActionPerformed(evt);
            }
        });
        jMenu1.add(Pesquisa_Assinatura);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void Cadastro_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_ClienteActionPerformed
        Tela_cad_cliente tel = new Tela_cad_cliente(DaoFactory.createAssinaturaDao().readAll(), 
                DaoFactory.createForma_pagamentoDao().readAll(), DaoFactory.createEnderecoDao().readAll());
        tel.setVisible(true);
    }//GEN-LAST:event_Cadastro_ClienteActionPerformed

    private void Cadastro_AssinaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_AssinaturaActionPerformed
        Tela_cad_assin tel = new Tela_cad_assin();
        tel.setVisible(true);
    }//GEN-LAST:event_Cadastro_AssinaturaActionPerformed

    private void Pesquisa_AssinaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pesquisa_AssinaturaActionPerformed
        Tela_consulta_assinatura tel =  new Tela_consulta_assinatura(DaoFactory.createAssinaturaDao().readAll());
        tel.setVisible(true);
    }//GEN-LAST:event_Pesquisa_AssinaturaActionPerformed

    private void Pesquisa_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pesquisa_ClienteActionPerformed
        Tela_consulta_cliente tel =  new Tela_consulta_cliente(DaoFactory.createClienteDao().readAll());
        tel.setVisible(true);
    }//GEN-LAST:event_Pesquisa_ClienteActionPerformed

    private void EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnderecoActionPerformed
        Tela_cad_endereco tel = new Tela_cad_endereco(DaoFactory.createEstadoDao().readAll());
        tel.setVisible(true);
    }//GEN-LAST:event_EnderecoActionPerformed

    private void Forma_pagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Forma_pagamentoActionPerformed
        Tela_cad_pagamento tel = new Tela_cad_pagamento(DaoFactory.createForma_pagamentoDao().readAll());
        tel.setVisible(true);
    }//GEN-LAST:event_Forma_pagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cadastro_Assinatura;
    private javax.swing.JMenuItem Cadastro_Cliente;
    private javax.swing.JMenuItem Endereco;
    private javax.swing.JMenuItem Forma_pagamento;
    private javax.swing.JMenuItem Pesquisa_Assinatura;
    private javax.swing.JMenuItem Pesquisa_Cliente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
