/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.univates.apresentacao;

import br.univates.negocio.Assinatura;
import br.univates.negocio.Cliente;
import br.univates.negocio.Endereco;
import br.univates.negocio.Forma_pagamento;
import br.univates.persistencia.DaoFactory;
import br.univates.source.persistence.IDao;
import br.univates.source.persistence.InvalidKeyException;
import br.univates.source.persistence.KeyViolationException;
import br.univates.source.persistence.NotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author nicol
 */
public class Tela_cad_cliente extends javax.swing.JFrame {

    /**
     * Creates new form Tela_cad_cliente
     */
    private Cliente cli;
    
    public Tela_cad_cliente(ArrayList<Assinatura> assiValidas, ArrayList<Forma_pagamento> pagamValidas, ArrayList<Endereco> enValidos) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cli=new Cliente();
        this.initCombos(pagamValidas, assiValidas, enValidos);
        
    }
    
    public void initCombos(ArrayList<Forma_pagamento> pagValidas, ArrayList<Assinatura> assiValidas, ArrayList<Endereco> enValidos)
    {
        this.Combo_assinaturas.removeAllItems();
        this.Combo_forma_pag.removeAllItems();
        this.Combo_Endereco.removeAllItems();
        for (Assinatura assi: assiValidas)
        {
            this.Combo_assinaturas.addItem(assi);
        }
        
        for (Forma_pagamento forma: pagValidas)
        {
            this.Combo_forma_pag.addItem(forma);
        }
        
        for (Endereco ende: enValidos)
        {
            this.Combo_Endereco.addItem(ende);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Combo_assinaturas = new javax.swing.JComboBox<>();
        Campo_Cpf = new javax.swing.JTextField();
        Campo_Nome = new javax.swing.JTextField();
        Campo_Email = new javax.swing.JTextField();
        Campo_assi_ativa = new javax.swing.JTextField();
        Campo_Telefone = new javax.swing.JTextField();
        Combo_forma_pag = new javax.swing.JComboBox<>();
        ButtonCancelar = new javax.swing.JButton();
        ButtonDeletar = new javax.swing.JButton();
        ButtonAtualizar = new javax.swing.JButton();
        ButtonCadastrar = new javax.swing.JButton();
        Combo_Endereco = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CPF do cliente");

        jLabel2.setText("Nome:");

        jLabel3.setText("Email:");

        jLabel4.setText("Assi_ativa:");

        jLabel5.setText("Telefone:");

        jLabel6.setText("Forma_pagamento:");

        jLabel7.setText("idEndereco:");

        jLabel8.setText("Assinatura:");

        Combo_assinaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_assinaturasActionPerformed(evt);
            }
        });

        Campo_assi_ativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_assi_ativaActionPerformed(evt);
            }
        });

        Campo_Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_TelefoneActionPerformed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        ButtonDeletar.setText("Deletar");
        ButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeletarActionPerformed(evt);
            }
        });

        ButtonAtualizar.setText("Atualizar");
        ButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAtualizarActionPerformed(evt);
            }
        });

        ButtonCadastrar.setText("Cadastrar");
        ButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarActionPerformed(evt);
            }
        });

        Combo_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_EnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Campo_assi_ativa)
                            .addComponent(Combo_Endereco, 0, 80, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Campo_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Campo_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Campo_Nome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Campo_Email, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Combo_assinaturas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_forma_pag, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(ButtonCancelar)
                .addGap(18, 18, 18)
                .addComponent(ButtonDeletar)
                .addGap(18, 18, 18)
                .addComponent(ButtonAtualizar)
                .addGap(18, 18, 18)
                .addComponent(ButtonCadastrar)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(Campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(Campo_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(Campo_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(Combo_assinaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Campo_assi_ativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(Campo_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Combo_forma_pag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Combo_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCancelar)
                    .addComponent(ButtonDeletar)
                    .addComponent(ButtonAtualizar)
                    .addComponent(ButtonCadastrar))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Campo_TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_TelefoneActionPerformed

    private void Campo_assi_ativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_assi_ativaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_assi_ativaActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void ButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeletarActionPerformed
        IDao<Cliente,String> dao= DaoFactory.createClienteDao();
        
        try {
            dao.delete(this.Campo_Cpf.getText());
            JOptionPane.showMessageDialog(null, "Deletado.", "Concluído", JOptionPane.INFORMATION_MESSAGE);
        } catch (NotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível deletar.", "Problema", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ButtonDeletarActionPerformed

    private void ButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAtualizarActionPerformed
        String cpf = (this.Campo_Cpf.getText());
        String nome = this.Campo_Nome.getText();
        String email = this.Campo_Email.getText();
        String assi_atv = (this.Campo_assi_ativa.getText());
        String tele = (this.Campo_Telefone.getText());
        Forma_pagamento forma = (Forma_pagamento) (this.Combo_forma_pag.getSelectedItem());
        Endereco en =(Endereco)(this.Combo_Endereco.getSelectedItem());
        Assinatura assi = (Assinatura) (this.Combo_assinaturas.getSelectedItem());
        

        boolean create = (this.cli.getCpf() == null);

        try {
            this.cli.setCpf(cpf);
        } catch (IOException ex) {
            Logger.getLogger(Tela_cad_cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.cli.setNome(nome);
        this.cli.setEmail(email);
        try {
            this.cli.setAss_atv(assi_atv);
        } catch (IOException ex) {
            Logger.getLogger(Tela_cad_cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.cli.setTelefone(tele);
        this.cli.setForma_pag(forma);
        this.cli.setEndereco(en);
        this.cli.setAssinatura(assi);

        IDao<Cliente, String> dao = DaoFactory.createClienteDao();

        try {
            if (create) {
                dao.update(cli);
            }
        } catch (NotFoundException ex) {
            Logger.getLogger(Tela_cad_cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_ButtonAtualizarActionPerformed

    private void ButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarActionPerformed
        String cpf = (this.Campo_Cpf.getText());
        String nome = this.Campo_Nome.getText();
        String email = this.Campo_Email.getText();
        String assi_atv = (this.Campo_assi_ativa.getText());
        String tele = (this.Campo_Telefone.getText());
        Forma_pagamento forma = (Forma_pagamento) (this.Combo_forma_pag.getSelectedItem());
        Endereco en =(Endereco)(this.Combo_Endereco.getSelectedItem());
        Assinatura assi = (Assinatura) (this.Combo_assinaturas.getSelectedItem());
        

        boolean create = (this.cli.getCpf() == null);

        try {
            this.cli.setCpf(cpf);
        } catch (IOException ex) {
            Logger.getLogger(Tela_cad_cliente.class.getName()).log(Level.SEVERE, "Erro com o cpf.", ex);
        }
        this.cli.setNome(nome);
        this.cli.setEmail(email);
        try {
            this.cli.setAss_atv(assi_atv);
        } catch (IOException ex) {
            Logger.getLogger(Tela_cad_cliente.class.getName()).log(Level.SEVERE, "Erro com a assinatura ativa.", ex);
        }
        this.cli.setTelefone(tele);
        this.cli.setForma_pag(forma);
        this.cli.setEndereco(en);
        this.cli.setAssinatura(assi);

        IDao<Cliente, String> dao = DaoFactory.createClienteDao();

        try {
            if (create) {
                dao.create(cli);
            }
        } catch (KeyViolationException | InvalidKeyException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        dispose();
    }//GEN-LAST:event_ButtonCadastrarActionPerformed

    private void Combo_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_EnderecoActionPerformed

    private void Combo_assinaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_assinaturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_assinaturasActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAtualizar;
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonDeletar;
    private javax.swing.JTextField Campo_Cpf;
    private javax.swing.JTextField Campo_Email;
    private javax.swing.JTextField Campo_Nome;
    private javax.swing.JTextField Campo_Telefone;
    private javax.swing.JTextField Campo_assi_ativa;
    private javax.swing.JComboBox<Endereco> Combo_Endereco;
    private javax.swing.JComboBox<Assinatura> Combo_assinaturas;
    private javax.swing.JComboBox<Forma_pagamento> Combo_forma_pag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
