/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.univates.apresentacao;

import br.univates.negocio.Endereco;
import br.univates.negocio.Estado;
import br.univates.persistencia.DaoFactory;
import br.univates.source.persistence.IDao;
import br.univates.source.persistence.InvalidKeyException;
import br.univates.source.persistence.KeyViolationException;
import br.univates.source.persistence.NotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class Tela_cad_endereco extends javax.swing.JFrame {

    /**
     * Creates new form Tela_cad_endereco
     */
    private Endereco en;

    public Tela_cad_endereco(ArrayList<Estado> estadosValidos) {
        initComponents();
        
        this.initCombos(estadosValidos);
        this.setLocationRelativeTo(null);
        en=new Endereco();
    }

    public void initCombos(ArrayList<Estado> estadosValidos)
    {
        this.ComboEstado.removeAllItems();
        for (Estado estado: estadosValidos)
        {
            ComboEstado.addItem(estado);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancelar = new javax.swing.JButton();
        btCriar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        BtAtualizar = new javax.swing.JButton();
        textoID = new javax.swing.JTextField();
        lbEn = new javax.swing.JLabel();
        textoRua = new javax.swing.JTextField();
        lbRua = new javax.swing.JLabel();
        lbBai = new javax.swing.JLabel();
        lbCid = new javax.swing.JLabel();
        lbEst = new javax.swing.JLabel();
        textoBairro = new javax.swing.JTextField();
        textoCidade = new javax.swing.JTextField();
        ComboEstado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TextoNumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btCriar.setText("Cadastrar");
        btCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarActionPerformed(evt);
            }
        });

        btDeletar.setText("Deletar");
        btDeletar.setToolTipText("Só é necessário o ID para essa ação.");
        btDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDeletarMouseEntered(evt);
            }
        });
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        BtAtualizar.setText("Atualizar");
        BtAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAtualizarActionPerformed(evt);
            }
        });

        textoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoIDActionPerformed(evt);
            }
        });
        textoID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoIDKeyTyped(evt);
            }
        });

        lbEn.setText("ID do Endereco");

        textoRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRuaActionPerformed(evt);
            }
        });

        lbRua.setText("Rua");

        lbBai.setText("Bairro");

        lbCid.setText("Cidade");

        lbEst.setText("Estado");

        textoBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoBairroActionPerformed(evt);
            }
        });

        textoCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCidadeActionPerformed(evt);
            }
        });

        ComboEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboEstadoItemStateChanged(evt);
            }
        });
        ComboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEstadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDeletar)
                        .addGap(18, 18, 18)
                        .addComponent(BtAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btCriar)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbRua)
                                    .addComponent(lbEn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(textoID, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(119, 119, 119))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(textoRua, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbCid)
                                            .addComponent(lbBai)
                                            .addComponent(lbEst))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(textoBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                                .addComponent(textoCidade))
                                            .addComponent(ComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(80, 80, 80))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRua)
                    .addComponent(textoRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBai)
                    .addComponent(textoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCid)
                    .addComponent(textoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEst)
                    .addComponent(ComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btCriar)
                    .addComponent(btDeletar)
                    .addComponent(BtAtualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed

        Integer id = Integer.parseInt(this.textoID.getText());
        String rua = this.textoRua.getText();
        String bai = this.textoBairro.getText();
        int numero = Integer.parseInt(this.TextoNumero.getText());
        String cid = (this.textoCidade.getText());
        Estado es = (Estado)this.ComboEstado.getSelectedItem();
        

        boolean create = (this.en.getPk() == null);

        this.en.setPk(id);
        this.en.setRua(rua);
        this.en.setBairro(bai);
        this.en.setNumero(numero);
        this.en.setCidade(cid);
        this.en.setEstado(es);

        IDao<Endereco, Integer> dao = DaoFactory.createEnderecoDao();

        try {
            if (create) {
                dao.create(en);
            }
        } catch (KeyViolationException | InvalidKeyException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        dispose();
    }//GEN-LAST:event_btCriarActionPerformed

    private void btDeletarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeletarMouseEntered

    }//GEN-LAST:event_btDeletarMouseEntered

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        IDao<Endereco, Integer> dao = DaoFactory.createEnderecoDao();

        try {
            dao.delete(Integer.parseInt(this.textoID.getText()));
            JOptionPane.showMessageDialog(null, "Deletado.", "Concluído", JOptionPane.INFORMATION_MESSAGE);
        } catch (NotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível deletar.", "Problema", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btDeletarActionPerformed

    private void BtAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAtualizarActionPerformed
        IDao<Endereco, Integer> dao = DaoFactory.createEnderecoDao();

        Integer id = Integer.parseInt(this.textoID.getText());
        String rua = this.textoRua.getText();
        String bai = this.textoBairro.getText();
        int num = Integer.parseInt(this.TextoNumero.getText());
        String cid = (this.textoCidade.getText());
        Estado es = (Estado)this.ComboEstado.getSelectedItem();
        

        boolean update = (this.en.getPk() == 0);

        this.en.setPk(id);
        this.en.setRua(rua);
        this.en.setBairro(bai);
        this.en.setNumero(num);
        this.en.setCidade(cid);
        this.en.setEstado(es);

        try {
            if (update) {
                dao.update(en);
            }else{
                System.out.println("Erro com o ID.");
            }
        } catch (NotFoundException ex) {
            Logger.getLogger(Tela_cad_endereco.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_BtAtualizarActionPerformed

    private void textoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoIDActionPerformed

    }//GEN-LAST:event_textoIDActionPerformed

    private void textoIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoIDKeyPressed

    }//GEN-LAST:event_textoIDKeyPressed

    private void textoIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoIDKeyTyped
        int valor;
        if (this.textoID.getText().length() != 0) {
            try {
                valor = Integer.parseInt(this.textoID.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Esse campo só aceita números inteiros.", "Cuidado", JOptionPane.INFORMATION_MESSAGE);
                this.textoID.grabFocus();
            }
        }
    }//GEN-LAST:event_textoIDKeyTyped

    private void textoRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRuaActionPerformed

    private void textoBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoBairroActionPerformed

    private void textoCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCidadeActionPerformed
        int valor;
        if (this.textoCidade.getText().length() != 0) {
            try {
                valor = Integer.parseInt(this.textoCidade.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Esse campo só aceita números inteiros.", "Cuidado", JOptionPane.INFORMATION_MESSAGE);
                this.textoCidade.grabFocus();
            }
        }
    }//GEN-LAST:event_textoCidadeActionPerformed

    private void ComboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboEstadoActionPerformed

    private void ComboEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboEstadoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboEstadoItemStateChanged

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAtualizar;
    private javax.swing.JComboBox<Estado> ComboEstado;
    private javax.swing.JTextField TextoNumero;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCriar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbBai;
    private javax.swing.JLabel lbCid;
    private javax.swing.JLabel lbEn;
    private javax.swing.JLabel lbEst;
    private javax.swing.JLabel lbRua;
    private javax.swing.JTextField textoBairro;
    private javax.swing.JTextField textoCidade;
    private javax.swing.JTextField textoID;
    private javax.swing.JTextField textoRua;
    // End of variables declaration//GEN-END:variables
}
